### ISSUE TITLE
Empty lines in literal blocks require indentation

### ISSUE THREAD

**Issue by mienaikage** [Leont/yamlish#14]
Literal blocks currently cannot be parsed if they contain an empty line. To work around this, the empty line requires indentation.

`perl6 -e 'use YAMLish; try (load-yaml "example: |\n  test\n\n  fail"); say $! || "success"'`
```
Couldn't parse YAML
  in sub load-yaml at /home/danielmita/.rakudobrew/moar-nom/install/share/perl6/site/sources/9D54CB20630A6D95A459E8D21558CE9627DA4464 (YAMLish) line 735
  in block <unit> at -e line 1
```

`perl6 -e 'use YAMLish; try (load-yaml "example: |\n  test\n  \n  pass"); say $! || "success"'`
```
success
```

**Comment by Leont** [comment]
Yeah, that is a bug. I wrote an obvious fix but it seems to break tests. I'm not sure yet what's going on.

**Comment by Leont** [comment]
This is fixed in the latest version
