### ISSUE TITLE
Folded scalar indicator >

### ISSUE THREAD

**Issue by finanalyst** [Leont/yamlish#25]
The following quick test fails:
```perl6
use v6.c;
use Test;
use YAMLish;
my %h = load-yaml(q:to/YAML/);
    ---
    description: > This is a multiline
        text with folding
    YAML
is %h<description>, 'This is a multiline text with folding', '> test';
```
output is 
```
Couldn't parse YAML
  in sub load-yaml at /home/richard/rakudo/install/share/perl6/site/sources/90B49C4259B8728536A92B1405593401FE529DBC (YAMLish) line 951
  in block <unit> at yaml.p6 line 4
```

I wanted to have long readable lines for a config application I am writing.

In fact, omitting the `>` altogether generates valid YAML too and is correctly parsed by YAMLish.
That is
```perl6
use v6.c;
use Test;
use YAMLish;
my %h = load-yaml(q:to/YAML/);
    ---
    description: > This is a multiline
        text with folding
    YAML
is %h<description>, 'This is a multiline text with folding', '> test';
```
So, I am not sure what the difference is between using `>` and not is. But it took a while for me to find the reason valid YAML (according to `https://codebeautify.org/yaml-validator`) was failing with YAMLish

**Comment by Leont** [comment]
According to the spec: «This header is followed by a non-content line break with an optional comment. This is the only case where a comment must not be followed by additional comment lines.», and it seems libyaml also doesn't accept this (dying with «did not find expected comment or line break»).

I'm pretty sure YAMLish is doing the correct thing here.
