### ISSUE TITLE
Trailing Whitespace Breaks Parsing

### ISSUE THREAD

**Issue by tgt** [Leont/yamlish#3]
The following code causes a Failure. I've used `\c[SPACE]` to make it more clear where the trailing space is. Adding an extra space to the lines containing 3 and 4 causes it to parse successfully. I've checked that this is valid YAML using Perl 5's YAML::Tiny.

    use YAMLish;

    my $a = qq:to/END/;
    ---
    - 1
    - 2
    -\c[SPACE]
      - 3
      - 4
    END

    my $b = load-yaml($a);
                                      
    dd $b;

**Comment by Leont** [comment]
This seems to be a side-effect of an 'is this a bug or a feature' in perl6 itself (regarding the scope of temps inside a rule). I seem to have figured out how to work around it, but I hope this can be fixed in the language instead.

**Comment by Leont** [comment]
This should be fixed by 39cb2681
