### ISSUE TITLE
Error when using Anchors/Aliases: No method 'make-value' for YAMLish::Alias

### ISSUE THREAD

**Issue by caseyjackmiles** [Leont/yamlish#33]
Running into errors when using anchors within YAML. YAMLish is able to load YAML containing anchors. But if my YAML refers to an anchor using `*`, the program throws an error.

I was attempting to merge maps using `<<` but was able to cause an error with a minimal anchor example, below.

**YAMLish version:** 0.0.5
**Raku version:** 6.d, Rakudo version 2020.01, MoarVM 2020.01.1
**Program contents:**
```raku
use YAMLish;

my $yaml = Q:to<END>;
anchored_key: &anchor_name This string will appear as the value of two keys.
other_key: *anchor_name
END

load-yaml($yaml);
```

**Program error output:**
```
﻿Couldn't parse YAML: No such method 'make-value' for invocant of type 'YAMLish::Alias'
  in sub load-yaml at /usr/local/Cellar/rakudo-star/2020.01_1/share/perl6/site/sources/ADB31520994572F18CE4EC4457E5E9321A31301C (YAMLish) line 948
  in block <unit> at yaml-anchor.raku line 8
```

**Comment by Leont** [comment]
It seems I have no one but two bugs coming together here, both are fixed in master now :-)

**Comment by caseyjackmiles** [comment]
Awesome, thanks @Leont! I pulled the latest code from `master` and tested it with the example above and it worked as expected. :sunglasses: 

> I was attempting to merge maps using << but was able to cause an error with a minimal anchor example, below.

It's a bit outside the scope of this issue, but: Should `<<`-merging be working while loading YAML, or is that not yet supported by YAMLish?

**Comment by Leont** [comment]
> Should <<-merging be working while loading YAML, or is that not yet supported by YAMLish?

That is not yet supported.
