### ISSUE TITLE
Symbolic links in `test-suite/meta` can cause problems on Windows

### ISSUE THREAD

**Issue by zb226** [Leont/yamlish#37]
I couldn't install `YAMLish` on Windows 10 and opened a [question on StackOverflow](https://stackoverflow.com/q/77372395/1529709) and subsequently an [issue for `zef`](https://github.com/ugexe/zef/issues/533).

It turns out that the symlinks in the test suite cause installation via `zef install YAMLish` to fail when it is neither run
- as administrator or
- in Windows Developer Mode

because creating symlinks is prohibited otherwise.

Both ugexe and raiph suggested opening an issue here to propose considering either
- somehow not use symlinks or
- mention this issue in the install messages or documentation

...which is what I'm doing here :) Cheers!

**Comment by Leont** [comment]
Those files are only used for the spec tests not for user tests. I should probably just release the dist to fez without them.

**Comment by Leont** [comment]
Seems resolved in 0.1.0
