### ISSUE TITLE
... should be optional

### ISSUE THREAD

**Issue by tgt** [Leont/yamlish#4]
As of https://github.com/Leont/yamlish/commit/9294458b7a4b7884b9731b84c2c88eb0bc16f111 the `...` document footer is now required when parsing. I think it should be optional.

    ---
    - default

That fails to parse since there's no `...` on the line after `- default`.

**Comment by Leont** [comment]
The issue is more delicate than that. It's not that it demands the `...`, it's that it got confused by a newline without a `...` marker following it. Either way, this should be fixes by 306ea23
