### ISSUE TITLE
depends on MIME::Base64 which fails to install

### ISSUE THREAD

**Issue by dnebauer** [Leont/yamlish#8]
Installation attempt on debian:

	$ panda install YAMLish
	==> YAMLish depends on MIME::Base64
	==> Fetching MIME::Base64
	==> Building MIME::Base64
	==> Testing MIME::Base64
	This type does not support elems
	  in any  at gen/moar/m-Metamodel.nqp line 1723
	  in method decode at /path/to/.panda-work/1457229202_1/lib/MIME/Base64/Perl.pm6 line 103
	  in method decode-str at /path/to/.panda-work/1457229202_1/lib/MIME/Base64.pm6 line 10
	  in method decode_base64 at /path/to/.panda-work/1457229202_1/lib/MIME/Base64.pm6 line 19
	  in block <unit> at t/basic.t line 14
	
	# Looks like you planned 18 tests, but ran 1
	t/basic.t ................. 
	Dubious, test returned 255 (wstat 65280, 0xff00)
	Failed 17/18 subtests 
	t/binary-and-long-line.t .. ok
	t/oneline.t ............... ok
	This type does not support elems
	  in any  at gen/moar/m-Metamodel.nqp line 1723
	  in method decode at /path/to/.panda-work/1457229202_1/lib/MIME/Base64/Perl.pm6 line 103
	  in method decode-str at /path/to/.panda-work/1457229202_1/lib/MIME/Base64.pm6 line 10
	  in block <unit> at t/rfc4648-test-vector.t line 23
	
	# Looks like you planned 16 tests, but ran 7
	t/rfc4648-test-vector.t ... 
	Dubious, test returned 255 (wstat 65280, 0xff00)
	Failed 9/16 subtests 
	
	Test Summary Report
	-------------------
	t/basic.t               (Wstat: 65280 Tests: 1 Failed: 0)
	  Non-zero exit status: 255
	  Parse errors: Bad plan.  You planned 18 tests but ran 1.
	t/rfc4648-test-vector.t (Wstat: 65280 Tests: 7 Failed: 0)
	  Non-zero exit status: 255
	  Parse errors: Bad plan.  You planned 16 tests but ran 7.
	Files=4, Tests=21,  4 wallclock secs ( 0.02 usr  0.00 sys +  3.41 cusr  0.18 csys =  3.61 CPU)
	Result: FAIL

**Comment by Leont** [comment]
It works fine for me, probab;y [this commit](https://github.com/perl6/Perl6-MIME-Base64/commit/4316dbc86aa6003fc71b6db44b8b16ab9cff26c3) fixed this already.
