### ISSUE TITLE
Numeric strings should be quoted in YAML output

### ISSUE THREAD

**Issue by mkheironimus** [Leont/yamlish#9]
save-yaml writes numeric strings without quotes, which will make them load as numbers instead of strings when the file is read. Quoting will make sure the strings stay strings.

```perl6
> my %test = ( 'one' => '1' );
one => 1
> %test.perl
{:one("1")}
> use YAMLish;
> save-yaml(%test);
---
one: 1
...
> load-yaml('one: 1').perl;
{:one(1)}
> load-yaml('one: "1"').perl;
{:one("1")}
```

**Comment by Leont** [comment]
Yeah, I should probably have a much wider range of values that I always quote. The outputter is generally less mature than the parser, I should reconsider a lot of things in it to be honest
